///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelDataData {
/*
{
  "firstname": "abdddg",
  "lastname": "def",
  "email": "abc@gmail.com",
  "phonenumber": "898989898",
  "profileUrl": "hjhjhjhj",
  "usertypeid": 1,
  "googleID": "93",
  "active": 1,
  "user_id": 37,
  "iat": 1676442347,
  "exp": 1707978347
}
*/

  String? firstname;
  String? lastname;
  String? email;
  String? phonenumber;
  String? profileUrl;
  int? usertypeid;
  String? googleID;
  int? active;
  int? userId;
  int? iat;
  int? exp;

  LoginModelDataData({
    this.firstname,
    this.lastname,
    this.email,
    this.phonenumber,
    this.profileUrl,
    this.usertypeid,
    this.googleID,
    this.active,
    this.userId,
    this.iat,
    this.exp,
  });
  LoginModelDataData.fromJson(Map<String, dynamic> json) {
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    email = json['email']?.toString();
    phonenumber = json['phonenumber']?.toString();
    profileUrl = json['profileUrl']?.toString();
    usertypeid = json['usertypeid']?.toInt();
    googleID = json['googleID']?.toString();
    active = json['active']?.toInt();
    userId = json['user_id']?.toInt();
    iat = json['iat']?.toInt();
    exp = json['exp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['email'] = email;
    data['phonenumber'] = phonenumber;
    data['profileUrl'] = profileUrl;
    data['usertypeid'] = usertypeid;
    data['googleID'] = googleID;
    data['active'] = active;
    data['user_id'] = userId;
    data['iat'] = iat;
    data['exp'] = exp;
    return data;
  }
}

class LoginModelData {
/*
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJhYmRkZGciLCJsYXN0bmFtZSI6ImRlZiIsImVtYWlsIjoiYWJjQGdtYWlsLmNvbSIsInBob25lbnVtYmVyIjoiODk4OTg5ODk4IiwicHJvZmlsZVVybCI6ImhqaGpoamhqIiwidXNlcnR5cGVpZCI6MSwiZ29vZ2xlSUQiOiI5MyIsImFjdGl2ZSI6MSwidXNlcl9pZCI6MzcsImlhdCI6MTY3NjQ0MjM0NywiZXhwIjoxNzA3OTc4MzQ3fQ.eBa9efTJ_BBlLSxKZimX4bXSOvdufXodYjmKa1W8owc",
  "data": {
    "firstname": "abdddg",
    "lastname": "def",
    "email": "abc@gmail.com",
    "phonenumber": "898989898",
    "profileUrl": "hjhjhjhj",
    "usertypeid": 1,
    "googleID": "93",
    "active": 1,
    "user_id": 37,
    "iat": 1676442347,
    "exp": 1707978347
  }
}
*/

  String? token;
  LoginModelDataData? data;

  LoginModelData({
    this.token,
    this.data,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    data = (json['data'] != null) ? LoginModelDataData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['data'] = this.data!.toJson();
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJhYmRkZGciLCJsYXN0bmFtZSI6ImRlZiIsImVtYWlsIjoiYWJjQGdtYWlsLmNvbSIsInBob25lbnVtYmVyIjoiODk4OTg5ODk4IiwicHJvZmlsZVVybCI6ImhqaGpoamhqIiwidXNlcnR5cGVpZCI6MSwiZ29vZ2xlSUQiOiI5MyIsImFjdGl2ZSI6MSwidXNlcl9pZCI6MzcsImlhdCI6MTY3NjQ0MjM0NywiZXhwIjoxNzA3OTc4MzQ3fQ.eBa9efTJ_BBlLSxKZimX4bXSOvdufXodYjmKa1W8owc",
    "data": {
      "firstname": "abdddg",
      "lastname": "def",
      "email": "abc@gmail.com",
      "phonenumber": "898989898",
      "profileUrl": "hjhjhjhj",
      "usertypeid": 1,
      "googleID": "93",
      "active": 1,
      "user_id": 37,
      "iat": 1676442347,
      "exp": 1707978347
    }
  }
}
*/

  bool? success;
  String? message;
  LoginModelData? data;

  LoginModel({
    this.success,
    this.message,
    this.data,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
