name: thia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2
  dio: ^5.1.2
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.1
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.11
  google_fonts: ^4.0.1
#  google_fonts: ^4.0.5
  readmore: ^2.2.0
  syncfusion_flutter_datepicker: ^21.2.8
  lottie: ^2.3.2
  share_plus: ^6.3.4
#  share_plus: ^7.0.2
  upgrader: ^6.2.0
#  upgrader: ^7.0.1

  #  to restart app
  flutter_phoenix: ^1.1.1

  #  google_sign_in: ^5.4.3
  stream_chat_flutter: ^6.1.0
  #  dart_jsonwebtoken: ^2.6.4

  googleapis: ^11.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9

  firebase_auth: ^4.6.2
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  cloud_firestore: ^4.8.0
  firebase_in_app_messaging: ^0.7.3+2
  firebase_dynamic_links: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/no_data_found.json
