name: thia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.5
  google_fonts: ^3.0.1
  readmore: ^2.2.0
  syncfusion_flutter_datepicker: ^20.4.44
  lottie: ^2.2.0
  share_plus: ^4.5.0

#  google_sign_in: ^5.4.3
  stream_chat_flutter: ^5.2.0
#  dart_jsonwebtoken: ^2.6.4

  googleapis: ^10.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.7

  firebase_auth: ^4.3.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0
  cloud_firestore: ^4.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/no_data_found.json
