name: thia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.5
  google_fonts: ^3.0.1
  readmore: ^2.2.0
  syncfusion_flutter_datepicker: ^20.4.44

  google_sign_in: ^5.4.3
  stream_chat_flutter: ^5.2.0
  dart_jsonwebtoken: ^2.6.4

  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  cloud_firestore: ^4.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
