///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TodoModel {
/*
{
  "taskID": 24,
  "userID": 42,
  "classID": "1",
  "name": "abc",
  "details": "details",
  "duedate": "2023-02-15T00:00:00.000Z",
  "priority": 2,
  "length": null,
  "private": false,
  "time": null,
  "isCompleted": false,
  "createdBy": null,
  "isSubtask": null
}
*/

  int? taskID;
  int? userID;
  String? classID;
  String? name;
  String? details;
  String? duedate;
  int? priority;
  String? length;
  bool? private;
  String? time;
  bool? isCompleted;
  String? createdBy;
  String? isSubtask;

  TodoModel({
    this.taskID,
    this.userID,
    this.classID,
    this.name,
    this.details,
    this.duedate,
    this.priority,
    this.length,
    this.private,
    this.time,
    this.isCompleted,
    this.createdBy,
    this.isSubtask,
  });
  TodoModel.fromJson(Map<String, dynamic> json) {
    taskID = json['taskID']?.toInt();
    userID = json['userID']?.toInt();
    classID = json['classID']?.toString();
    name = json['name']?.toString();
    details = json['details']?.toString();
    duedate = json['duedate']?.toString();
    priority = json['priority']?.toInt();
    length = json['length']?.toString();
    private = json['private'];
    time = json['time']?.toString();
    isCompleted = json['isCompleted'];
    createdBy = json['createdBy']?.toString();
    isSubtask = json['isSubtask']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['taskID'] = taskID;
    data['userID'] = userID;
    data['classID'] = classID;
    data['name'] = name;
    data['details'] = details;
    data['duedate'] = duedate;
    data['priority'] = priority;
    data['length'] = length;
    data['private'] = private;
    data['time'] = time;
    data['isCompleted'] = isCompleted;
    data['createdBy'] = createdBy;
    data['isSubtask'] = isSubtask;
    return data;
  }
}

class CalenderTaskListModel {
/*
{
  "success": true,
  "message": "Success",
  "data": [
    {
      "taskID": 24,
      "userID": 42,
      "classID": "1",
      "name": "abc",
      "details": "details",
      "duedate": "2023-02-15T00:00:00.000Z",
      "priority": 2,
      "length": null,
      "private": false,
      "time": null,
      "isCompleted": false,
      "createdBy": null,
      "isSubtask": null
    }
  ]
}
*/

  bool? success;
  String? message;
  List<TodoModel?>? data;

  CalenderTaskListModel({
    this.success,
    this.message,
    this.data,
  });
  CalenderTaskListModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <TodoModel>[];
      v.forEach((v) {
        arr0.add(TodoModel.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class TodoModel {
// /*
// {
//   "taskID": 36,
//   "userID": 42,
//   "classID": "587252296793",
//   "name": "oooh",
//   "details": "saaa",
//   "duedate": "2023-02-26T08:00:00.000Z",
//   "priority": 3,
//   "private": true,
//   "time": "17:00:00.000000"
// }
// */
//
//   int? taskID;
//   int? userID;
//   String? classID;
//   String? name;
//   String? details;
//   String? duedate;
//   int? priority;
//   bool? private;
//   String? time;
//
//   TodoModel({
//     this.taskID,
//     this.userID,
//     this.classID,
//     this.name,
//     this.details,
//     this.duedate,
//     this.priority,
//     this.private,
//     this.time,
//   });
//   TodoModel.fromJson(Map<String, dynamic> json) {
//     taskID = json['taskID']?.toInt();
//     userID = json['userID']?.toInt();
//     classID = json['classID']?.toString();
//     name = json['name']?.toString();
//     details = json['details']?.toString();
//     duedate = json['duedate']?.toString();
//     priority = json['priority']?.toInt();
//     private = json['private'];
//     time = json['time']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['taskID'] = taskID;
//     data['userID'] = userID;
//     data['classID'] = classID;
//     data['name'] = name;
//     data['details'] = details;
//     data['duedate'] = duedate;
//     data['priority'] = priority;
//     data['private'] = private;
//     data['time'] = time;
//     return data;
//   }
// }
//
// class CalenderTaskListModel {
// /*
// {
//   "success": true,
//   "message": "Success",
//   "data": [
//     {
//       "taskID": 36,
//       "userID": 42,
//       "classID": "587252296793",
//       "name": "oooh",
//       "details": "saaa",
//       "duedate": "2023-02-26T08:00:00.000Z",
//       "priority": 3,
//       "private": true,
//       "time": "17:00:00.000000"
//     }
//   ]
// }
// */
//
//   bool? success;
//   String? message;
//   List<TodoModel?>? data;
//
//   CalenderTaskListModel({
//     this.success,
//     this.message,
//     this.data,
//   });
//   CalenderTaskListModel.fromJson(Map<String, dynamic> json) {
//     success = json['success'];
//     message = json['message']?.toString();
//     if (json['data'] != null) {
//       final v = json['data'];
//       final arr0 = <TodoModel>[];
//       v.forEach((v) {
//         arr0.add(TodoModel.fromJson(v));
//       });
//       this.data = arr0;
//     }
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['success'] = success;
//     data['message'] = message;
//     if (this.data != null) {
//       final v = this.data;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['data'] = arr0;
//     }
//     return data;
//   }
// }
