///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ClassUserModelData {
/*
{
  "userID": 40,
  "firstname": "abdddg",
  "lastname": "def",
  "middlename": "",
  "email": "abc@gmail.com",
  "phonenumber": "898989898",
  "active": true,
  "createdate": "2023-02-14T20:43:46.880Z",
  "usertypeid": 1,
  "profileUrl": "hjhjhjhj",
  "googleID": "103"
}
*/

  int? userID;
  String? firstname;
  String? lastname;
  String? middlename;
  String? email;
  String? phonenumber;
  bool? active;
  String? createdate;
  int? usertypeid;
  String? profileUrl;
  String? googleID;

  ClassUserModelData({
    this.userID,
    this.firstname,
    this.lastname,
    this.middlename,
    this.email,
    this.phonenumber,
    this.active,
    this.createdate,
    this.usertypeid,
    this.profileUrl,
    this.googleID,
  });
  ClassUserModelData.fromJson(Map<String, dynamic> json) {
    userID = json['userID']?.toInt();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    middlename = json['middlename']?.toString();
    email = json['email']?.toString();
    phonenumber = json['phonenumber']?.toString();
    active = json['active'];
    createdate = json['createdate']?.toString();
    usertypeid = json['usertypeid']?.toInt();
    profileUrl = json['profileUrl']?.toString();
    googleID = json['googleID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userID'] = userID;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['middlename'] = middlename;
    data['email'] = email;
    data['phonenumber'] = phonenumber;
    data['active'] = active;
    data['createdate'] = createdate;
    data['usertypeid'] = usertypeid;
    data['profileUrl'] = profileUrl;
    data['googleID'] = googleID;
    return data;
  }
}

class ClassUserModel {
/*
{
  "success": true,
  "message": "Success",
  "data": [
    {
      "userID": 40,
      "firstname": "abdddg",
      "lastname": "def",
      "middlename": "",
      "email": "abc@gmail.com",
      "phonenumber": "898989898",
      "active": true,
      "createdate": "2023-02-14T20:43:46.880Z",
      "usertypeid": 1,
      "profileUrl": "hjhjhjhj",
      "googleID": "103"
    }
  ]
}
*/

  bool? success;
  String? message;
  List<ClassUserModelData?>? data;

  ClassUserModel({
    this.success,
    this.message,
    this.data,
  });
  ClassUserModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ClassUserModelData>[];
      v.forEach((v) {
        arr0.add(ClassUserModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
