///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetPriorityCountData {
/*
{
  "High": 0,
  "Medium": 0,
  "Low": 0
}
*/

  int? high;
  int? medium;
  int? low;

  GetPriorityCountData({
    this.high,
    this.medium,
    this.low,
  });
  GetPriorityCountData.fromJson(Map<String, dynamic> json) {
    high = json['High']?.toInt();
    medium = json['Medium']?.toInt();
    low = json['Low']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['High'] = high;
    data['Medium'] = medium;
    data['Low'] = low;
    return data;
  }
}

class GetPriorityCount {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "High": 0,
    "Medium": 0,
    "Low": 0
  }
}
*/

  bool? success;
  String? message;
  GetPriorityCountData? data;

  GetPriorityCount({
    this.success,
    this.message,
    this.data,
  });
  GetPriorityCount.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? GetPriorityCountData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
