///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TaskDetailModelDataSubTask {
/*
{
  "subtaskid": 6,
  "name": "XYZ",
  "details": "hjhjhj",
  "duedate": "2023-02-15T00:00:00.000Z",
  "taskid": 57,
  "iscomplete": false
}
*/

  int? subtaskid;
  String? name;
  String? details;
  String? duedate;
  int? taskid;
  bool? iscomplete;

  TaskDetailModelDataSubTask({
    this.subtaskid,
    this.name,
    this.details,
    this.duedate,
    this.taskid,
    this.iscomplete,
  });
  TaskDetailModelDataSubTask.fromJson(Map<String, dynamic> json) {
    subtaskid = json['subtaskid']?.toInt();
    name = json['name']?.toString();
    details = json['details']?.toString();
    duedate = json['duedate']?.toString();
    taskid = json['taskid']?.toInt();
    iscomplete = json['iscomplete'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subtaskid'] = subtaskid;
    data['name'] = name;
    data['details'] = details;
    data['duedate'] = duedate;
    data['taskid'] = taskid;
    data['iscomplete'] = iscomplete;
    return data;
  }

  setName(String val) {
    name = val;
  }

  setComplete(bool val) {
    iscomplete = val;
  }
}

class TaskDetailModelData {
/*
{
  "taskID": 57,
  "userID": 52,
  "classID": "78908787uui",
  "name": "abc",
  "details": "detailll",
  "duedate": "2023-02-15T00:00:00.000Z",
  "priority": 2,
  "length": null,
  "private": false,
  "time": "11:00:00.0000000",
  "isCompleted": false,
  "createdBy": "abdddg",
  "isSubtask": true,
  "subTask": [
    {
      "subtaskid": 6,
      "name": "XYZ",
      "details": "hjhjhj",
      "duedate": "2023-02-15T00:00:00.000Z",
      "taskid": 57,
      "iscomplete": false
    }
  ]
}
*/

  int? taskID;
  int? userID;
  String? classID;
  String? name;
  String? details;
  String? duedate;
  int? priority;
  String? length;
  bool? private;
  String? time;
  bool? isCompleted;
  String? createdBy;
  bool? isSubtask;
  List<TaskDetailModelDataSubTask?>? subTask;

  TaskDetailModelData({
    this.taskID,
    this.userID,
    this.classID,
    this.name,
    this.details,
    this.duedate,
    this.priority,
    this.length,
    this.private,
    this.time,
    this.isCompleted,
    this.createdBy,
    this.isSubtask,
    this.subTask,
  });
  TaskDetailModelData.fromJson(Map<String, dynamic> json) {
    taskID = json['taskID']?.toInt();
    userID = json['userID']?.toInt();
    classID = json['classID']?.toString();
    name = json['name']?.toString();
    details = json['details']?.toString();
    duedate = json['duedate']?.toString();
    priority = json['priority']?.toInt();
    length = json['length']?.toString();
    private = json['private'];
    time = json['time']?.toString();
    isCompleted = json['isCompleted'];
    createdBy = json['createdBy']?.toString();
    isSubtask = json['isSubtask'];
    if (json['subTask'] != null) {
      final v = json['subTask'];
      final arr0 = <TaskDetailModelDataSubTask>[];
      v.forEach((v) {
        arr0.add(TaskDetailModelDataSubTask.fromJson(v));
      });
      subTask = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['taskID'] = taskID;
    data['userID'] = userID;
    data['classID'] = classID;
    data['name'] = name;
    data['details'] = details;
    data['duedate'] = duedate;
    data['priority'] = priority;
    data['length'] = length;
    data['private'] = private;
    data['time'] = time;
    data['isCompleted'] = isCompleted;
    data['createdBy'] = createdBy;
    data['isSubtask'] = isSubtask;
    if (subTask != null) {
      final v = subTask;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subTask'] = arr0;
    }
    return data;
  }
}

class TaskDetailModel {
/*
{
  "success": true,
  "message": "Success",
  "data": {
    "taskID": 57,
    "userID": 52,
    "classID": "78908787uui",
    "name": "abc",
    "details": "detailll",
    "duedate": "2023-02-15T00:00:00.000Z",
    "priority": 2,
    "length": null,
    "private": false,
    "time": "11:00:00.0000000",
    "isCompleted": false,
    "createdBy": "abdddg",
    "isSubtask": true,
    "subTask": [
      {
        "subtaskid": 6,
        "name": "XYZ",
        "details": "hjhjhj",
        "duedate": "2023-02-15T00:00:00.000Z",
        "taskid": 57,
        "iscomplete": false
      }
    ]
  }
}
*/

  bool? success;
  String? message;
  TaskDetailModelData? data;

  TaskDetailModel({
    this.success,
    this.message,
    this.data,
  });
  TaskDetailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? TaskDetailModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
