///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllNotificationModelData {
/*
{
  "userID": 110,
  "accepted": true,
  "rejected": false,
  "channel_id": "516573860629",
  "channel_name": "Pratik",
  "channel_image": "https://i.imgur.com/ReSxSJU.png",
  "nid": 1,
  "invite_by": "Wall world"
}
*/

  int? userID;
  bool? accepted;
  bool? rejected;
  String? channelId;
  String? channelName;
  String? channelImage;
  int? nid;
  String? inviteBy;

  AllNotificationModelData({
    this.userID,
    this.accepted,
    this.rejected,
    this.channelId,
    this.channelName,
    this.channelImage,
    this.nid,
    this.inviteBy,
  });

  AllNotificationModelData.fromJson(Map<String, dynamic> json) {
    userID = json['userID']?.toInt();
    accepted = json['accepted'];
    rejected = json['rejected'];
    channelId = json['channel_id']?.toString();
    channelName = json['channel_name']?.toString();
    channelImage = json['channel_image']?.toString();
    nid = json['nid']?.toInt();
    inviteBy = json['invite_by']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userID'] = userID;
    data['accepted'] = accepted;
    data['rejected'] = rejected;
    data['channel_id'] = channelId;
    data['channel_name'] = channelName;
    data['channel_image'] = channelImage;
    data['nid'] = nid;
    data['invite_by'] = inviteBy;
    return data;
  }
}

class AllNotificationModel {
/*
{
  "success": true,
  "message": "Success",
  "data": [
    {
      "userID": 110,
      "accepted": true,
      "rejected": false,
      "channel_id": "516573860629",
      "channel_name": "Pratik",
      "channel_image": "https://i.imgur.com/ReSxSJU.png",
      "nid": 1,
      "invite_by": "Wall world"
    }
  ]
}
*/

  bool? success;
  String? message;
  List<AllNotificationModelData?>? data;

  AllNotificationModel({
    this.success,
    this.message,
    this.data,
  });

  AllNotificationModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AllNotificationModelData>[];
      v.forEach((v) {
        arr0.add(AllNotificationModelData.fromJson(v));
      });
      data = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
