///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GenerateDeepLinkModelData {
/*
{
  "url": "https://thia.page.link/fMNh?name=Ujas&Id=12&"
}
*/

  String? url;

  GenerateDeepLinkModelData({
    this.url,
  });
  GenerateDeepLinkModelData.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    return data;
  }
}

class GenerateDeepLinkModel {
/*
{
  "success": true,
  "data": {
    "url": "https://thia.page.link/fMNh?name=Ujas&Id=12&"
  }
}
*/

  bool? success;
  GenerateDeepLinkModelData? data;

  GenerateDeepLinkModel({
    this.success,
    this.data,
  });
  GenerateDeepLinkModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? GenerateDeepLinkModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['data'] = this.data!.toJson();
    return data;
  }
}
